version: "3.9"

services:
    database:
      image: "postgres:11-alpine"
      env_file: "./environment/database.env"
      ports:
        - 5432:5432
      volumes:
        - ./database-market:/var/lib/postgresql/data

volumes:
  database-market:

